HH-124106 add sync cached based on consul blocking queries
hhru/python-consul2 pull request #3
Opened 2021-02-17 15:59 UTC by nicholasgribanov

2021-02-17 16:14 UTC, dzharikhin commented on consul/base.py
> +        self._cache_process = threading.Thread(target=self._update_cache, daemon=True)
_cache_process -> _cache_thread

2021-02-17 16:16 UTC, dzharikhin approved these changes

2021-02-17 16:34 UTC, bokshitsky commented on consul/base.py
> +    def add_listener(self, callback, trigger_current=False):
Возможно, правильнее чтобы callback не только value принимал но и key

2021-02-17 16:36 UTC, bokshitsky commented on consul/base.py
> +    def add_listener(self, callback, trigger_current=False):
А зачем, кстати, там в cache лежит dict всегда из 1-го элемента?

2021-02-17 16:37 UTC, bokshitsky commented on consul/base.py
> +            self.index, values = self.health_client.service(**params)
long_pooling и блокировка на строчк
` self.index, values = self.health_client.service(**params)` происходит?

2021-02-17 16:39 UTC, bokshitsky commented on consul/base.py
> +        self.watch_seconds = watch_seconds
для watch_seconds как параметра этот Cache-объекта имя бы какое-нибудь другое дать, просто щас непотяно что оно значит.
По факту же это сколько максимально по времени держать long-pooling соединение, в случае если ничего не изменится в консуле за это время?

2021-02-17 16:43 UTC, bokshitsky commented on consul/base.py
> +            if self.callbacks and self._running:
это на вкус канеш, но я бы инвертировал логику проверок с ранним выхходом на continue
чтобы пирамидку чутка разгрузить

2021-02-17 17:38 UTC, sintell requested changes

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +class ConsulCacheBase(object):
не надо от object наследоваться

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +        self._cache_process = threading.Thread(target=self._update_cache, daemon=True)
Я бы еще какой-нибудь понятный `name` задал бы, чтобы в трейсбеках можно было бы следить и для метрик может пригодиться

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +    def _update_cache(self):
Если не предполагается, что этот класс кто-то будет использовать напрямую, то я бы его объявил бы как
```py
class ConsulCacheBase(metaclass=ABCMeta):
...
```
А на этот метод повесил бы 
`@abstractmethod`

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +        ConsulCacheBase.__init__(self, watch_seconds)
лучше всегда использовать `super().__init__`. Тут это не критично, но если вдруг базщовый класс будет использовать множественное наследование то тут все развалится

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +    def __init__(self, health_client, watch_seconds, service, passing):
Укажи, пожалуйста типы аргументов, тут они совсем не очевидны

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +    def __init__(self, health_client, watch_seconds, service, passing):
И, возможно стоит и значение некоторых пояснить, в докстринге, например - что такое `passing`

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +        while self._running:
Красивее было бы сделать на `Event()`, но так как тут всего один тред, то не принципиально. Кстати, если тред и должен будет остаться один, то можно подумать о том, чтобы просто унаследоваться от threading.Thread и переопределить `run`

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +            self.index, values = self.health_client.service(**params)
Судя по тому, что мы в ответ получаем сразу значения, то вызов блокирующий.
А ошибки тут обработать не нужно? Они могут быть?

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +            old_cache = self.cache
А эта строчка не должна быть раньше предыдущей?

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +            if self.callbacks and self._running:
Нет смысла тут повторно проверять на is_running, потому что до этого момента никто не успеет этот флаг поменять.

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +                    new_value = self.cache.get(key, None)
А в чем логика `callback(None)`?

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +        self.consistency_mode = consistency_mode
Выглядит так, как будто это должен быть `Enum`

2021-02-17 17:38 UTC, sintell commented on consul/base.py
> +                    if old_value != new_value:
Значения каких типов тут могут быть?

2021-02-17 17:39 UTC, sintell commented on consul/base.py
> +class ConsulCacheException(Exception):
Не нашел использований, заче эта ошибка?

2021-02-17 17:42 UTC, sintell commented on consul/base.py
> +            for key, value in self.cache:
Так не сработает, надо `in self.items()`

2021-02-17 17:45 UTC, bokshitsky commented on consul/base.py
> +            if self.callbacks and self._running:
могут по идее, тут ведь отдельный тред

2021-02-17 19:03 UTC, dzharikhin commented on consul/base.py
> +        self.cache = {self.path: kv_client.get(path)[1]}
вот тут давай-ка заложим-ка кастомный таймаут?
отхожим местом чую - понадобится он

2021-02-17 19:27 UTC, sintell commented on consul/base.py
> +            if self.callbacks and self._running:
Да, я чот плохо подумал, в теории GIL гарантирует эксклюзивный доступ, но тут будет блокировка на моменте `self.health_client.service` и вот тут может блокировка пройти

2021-02-18 09:05 UTC, nicholasgribanov commented on consul/base.py
> +        self.watch_seconds = watch_seconds
Тут все так, это дань унификации. У нас в клиенте джавовом и конфигах он так же называется. Мне кажется лучше оставить так, чтобы разъездов меньше было. Если переименовывать, то по хорошему и в конфигах и в джавовом клиенте. Что думаешь?

2021-02-18 09:13 UTC, nicholasgribanov commented on consul/base.py
> +        self._cache_process = threading.Thread(target=self._update_cache, daemon=True)
А есть конвенция как имена тредам давать в питоне? snake-case, camel-case?

2021-02-18 09:14 UTC, nicholasgribanov commented on consul/base.py
> +    def add_listener(self, callback, trigger_current=False):
Прав, для текущих кешей это не нужно, но кажется, что при расширении могут быть разные варианты наполнения кеша с ключами. И да, тогда имеет смысл key тоже передавать в callback.

2021-02-18 09:20 UTC, nicholasgribanov commented on consul/base.py
> +                    new_value = self.cache.get(key, None)
Ничего не получили из KV хранилища консула, должны в сервисе задать значение по умолчанию

2021-02-18 09:52 UTC, sintell commented on consul/base.py
> +        self._cache_process = threading.Thread(target=self._update_cache, daemon=True)
не, нет какой-то особой, по-умолчанию они называются как `Thread-N`, где N это small int

2021-02-19 06:10 UTC, nicholasgribanov commented on consul/base.py
> +            self.index, values = self.health_client.service(**params)
Ошибки быть могут. Мы допускаем только 404, в случае других ошибок нужно выбрасывать исключение. Вот тут описаны ошибки, которые могу возникнуть https://github.com/hhru/python-consul2/blob/b08572694f56ff9657effb4b34c40b861a9f14a4/consul/base.py#L208

2021-02-19 08:18 UTC, dzharikhin commented on consul/base.py
> +        self.watch_seconds = watch_seconds
думаю, надо оставить

2021-02-19 08:18 UTC, dzharikhin commented on consul/base.py
> +                 total_timeout: int,
cache_initial_warmup_timeout? и наверное этот параметр необязательный. если меня общий таймаут устраивает, то че бы нет

2021-02-19 08:41 UTC, nicholasgribanov commented on consul/base.py
> +                 total_timeout: int,
Имеешь ввиду еще один параметр добавить, чтобы тут его использовать при инициализации кеша ? 
`self.cache = {self.path: kv_client.get(key=path, total_timeout=total_timeout)[1]}`

2021-02-19 16:08 UTC, sintell commented on consul/base.py
> +    def __init__(self, watch_seconds: str):
А watch_seconds точно должен быть str? Выглядит несколько нелогичным

2021-02-19 16:08 UTC, sintell commented on consul/base.py
> +                 health_client: 'Consul.Health',
А нельзя сюда просто заимпортить этот тип?

2021-02-19 16:11 UTC, sintell commented on consul/base.py
> +            self.index, values = self.health_client.service(**params)
Тогда обращаю внимание, что этот отдельный тред в случае эксепшена просто умрет )

2021-02-24 05:41 UTC, nicholasgribanov commented on consul/base.py
> +    def __init__(self, watch_seconds: str):
Да, это консула. Он в таком виде : 10s, 10m, 10ms передается

2021-02-24 05:41 UTC, nicholasgribanov commented on consul/base.py
> +                 health_client: 'Consul.Health',
Посмотрю что это такое ))

2021-02-24 05:43 UTC, nicholasgribanov commented on consul/base.py
> +            self.index, values = self.health_client.service(**params)
А вообще прав, я не подумал. Тред умрет, приложение будет дальше работать. Оберну в трай-кэтч, чтобы пока приложение живо поток пытался получить данные из консула

2021-02-24 05:52 UTC, nicholasgribanov commented on consul/base.py
> +                 health_client: 'Consul.Health',
А как его "заимпортить"?

2021-02-24 07:25 UTC, sintell commented on consul/base.py
> +                 health_client: 'Consul.Health',
Что такое health_client, откуда он возьмётся?

2021-02-24 07:29 UTC, sintell reviewed
Ещё пара моментов

2021-02-24 07:29 UTC, sintell commented on consul/base.py
> +                 consistency_mode: 'ConsistencyMode'):
Тут можно тип без кавычек указать, он же в этом же файле, выше, определён

2021-02-24 07:29 UTC, sintell commented on consul/base.py
> +            except Exception as e:
Использовать дженерный класс `Exception` считается плохой практикой, потому что:
- при добавлении нового кода можно забыть, что ловятся все ошибки и поймать лишнюю
- постороннему разработчику не очевидно какие именно ошибки тут могут возникнуть 

Тут точно нельзя указать конкретные ошибки, которые мы ждём?

2021-02-24 07:47 UTC, nicholasgribanov commented on consul/base.py
> +            except Exception as e:
Уточнил тип

2021-02-24 07:47 UTC, nicholasgribanov commented on consul/base.py
> +                 consistency_mode: 'ConsistencyMode'):
есть!

2021-02-24 07:54 UTC, sintell approved these changes

2021-02-24 09:54 UTC, merged